name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    env:
      BUILD_TAG: 0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        export BUILD_TAG=build-$(date -u +'%Y%m%d%H%M')
        echo "::set-env name=BUILD_TAG::$BUILD_TAG"

    - name: Compile code
      run: platformio run -e teensy41
